'server-only'

/**
* This file was generated by @vramework/cli@0.5.39
*/



/**
 * This file provides a wrapper around the VrameworkNextJS class to allow for methods to be type checked against your routes.
 * This ensures type safety for route handling methods when integrating with the `@vramework/core` framework.
 */
import { VrameworkNextJS } from '@vramework/next'
import type { RoutesMap, RouteHandlerOf } from '@todos/sdk/.vramework/routes-map.d'

import { createConfig as createConfig } from '@todos/functions/src/config'
import { createSingletonServices as createSingletonServices } from '@todos/functions/src/services'
import { createSessionServices as createSessionServices } from '@todos/functions/src/services'

import '@todos/functions/.vramework/vramework-routes'
import '@todos/functions/.vramework/vramework-schemas/register'

let _vramework: VrameworkNextJS | undefined

/**
 * Initializes and returns an instance of VrameworkNextJS with helper methods for handling route requests.
 *
 * @returns An object containing methods for making action requests, SSR requests, and API requests.
 */
export const vramework = () => {
  if (!_vramework) {
    _vramework = new VrameworkNextJS(
      createConfig as any,
      createSingletonServices as any,
      createSessionServices
    )
  }

  /**
   * Makes an action request for a specified route and method.
   *
   * @template Route - The route key from the RoutesMap.
   * @template Method - The method key from the specified route.
   * @param route - The route to make the request to.
   * @param method - The method to be used for the request.
   * @param data - The input data for the request.
   * @returns A promise that resolves to the output of the route handler.
   */
  const actionRequest = async <
    Route extends keyof RoutesMap,
    Method extends keyof RoutesMap[Route]
  >(
    route: Route,
    method: Method,
    data: RouteHandlerOf<Route, Method>['input']
  ): Promise<RouteHandlerOf<Route, Method>['output']> => {
    return _vramework!.actionRequest(route, method, data as any)
  }

  /**
   * Makes a static action request for a specified route and method.
   *
   * @template Route - The route key from the RoutesMap.
   * @template Method - The method key from the specified route.
   * @param route - The route to make the request to.
   * @param method - The method to be used for the request.
   * @param data - The input data for the request.
   * @returns A promise that resolves to the output of the route handler.
   */
  const staticActionRequest = async <
    Route extends keyof RoutesMap,
    Method extends keyof RoutesMap[Route]
  >(
    route: Route,
    method: Method,
    data: RouteHandlerOf<Route, Method>['input']
  ): Promise<RouteHandlerOf<Route, Method>['output']> => {
    return _vramework!.staticActionRequest(route, method, data as any)
  }

  return {
    staticActionRequest,
    actionRequest
  }
}